/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CareTasksRouteImport } from './routes/care-tasks'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantsAddRouteImport } from './routes/plants.add'

const CareTasksRoute = CareTasksRouteImport.update({
  id: '/care-tasks',
  path: '/care-tasks',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsAddRoute = PlantsAddRouteImport.update({
  id: '/plants/add',
  path: '/plants/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-tasks': typeof CareTasksRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-tasks': typeof CareTasksRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/care-tasks': typeof CareTasksRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/about' | '/care-tasks' | '/plants/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about' | '/care-tasks' | '/plants/add'
  id: '__root__' | '/' | '/about' | '/care-tasks' | '/plants/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareTasksRoute: typeof CareTasksRoute
  PlantsAddRoute: typeof PlantsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/care-tasks': {
      id: '/care-tasks'
      path: '/care-tasks'
      fullPath: '/care-tasks'
      preLoaderRoute: typeof CareTasksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/add': {
      id: '/plants/add'
      path: '/plants/add'
      fullPath: '/plants/add'
      preLoaderRoute: typeof PlantsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareTasksRoute: CareTasksRoute,
  PlantsAddRoute: PlantsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
