/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as InvoiceRouteImport } from './routes/invoice'
import { Route as CareTasksCalendarRouteImport } from './routes/care-tasks-calendar'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlantsAddRouteImport } from './routes/plants.add'

const InvoiceRoute = InvoiceRouteImport.update({
  id: '/invoice',
  path: '/invoice',
  getParentRoute: () => rootRouteImport,
} as any)
const CareTasksCalendarRoute = CareTasksCalendarRouteImport.update({
  id: '/care-tasks-calendar',
  path: '/care-tasks-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlantsAddRoute = PlantsAddRouteImport.update({
  id: '/plants/add',
  path: '/plants/add',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/care-tasks-calendar': typeof CareTasksCalendarRoute
  '/invoice': typeof InvoiceRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/care-tasks-calendar': typeof CareTasksCalendarRoute
  '/invoice': typeof InvoiceRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/care-tasks-calendar': typeof CareTasksCalendarRoute
  '/invoice': typeof InvoiceRoute
  '/plants/add': typeof PlantsAddRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/care-tasks-calendar' | '/invoice' | '/plants/add'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/care-tasks-calendar' | '/invoice' | '/plants/add'
  id: '__root__' | '/' | '/care-tasks-calendar' | '/invoice' | '/plants/add'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CareTasksCalendarRoute: typeof CareTasksCalendarRoute
  InvoiceRoute: typeof InvoiceRoute
  PlantsAddRoute: typeof PlantsAddRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/invoice': {
      id: '/invoice'
      path: '/invoice'
      fullPath: '/invoice'
      preLoaderRoute: typeof InvoiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/care-tasks-calendar': {
      id: '/care-tasks-calendar'
      path: '/care-tasks-calendar'
      fullPath: '/care-tasks-calendar'
      preLoaderRoute: typeof CareTasksCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plants/add': {
      id: '/plants/add'
      path: '/plants/add'
      fullPath: '/plants/add'
      preLoaderRoute: typeof PlantsAddRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CareTasksCalendarRoute: CareTasksCalendarRoute,
  InvoiceRoute: InvoiceRoute,
  PlantsAddRoute: PlantsAddRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
